baseURL = 'https://mkey.github.io'
languageCode = 'en-gb'
title = 'My New Hugo Site'
theme = 'risotto'
params.description = "Hugo Test Site"
params.author = "Marko K"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 2

[caches]
    [caches.images]
        dir = ':cacheDir/images'

